### ISSUE TITLE
error: Nothing matches

### ISSUE THREAD

**Issue by yougoticed79** [USA-RedDragon/jagex-launcher-linux-flatpak#115]
This is an issue with (choose one or more):

- [ ] RS3
- [ ] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [ x] Something else

**Describe the bug**
When attempting to install using the launcher i get an error saying "nothing matches com.jagex.Launcher in remote JagexLauncher. I am new to linux so im not sure if im missing something simple.
**To Reproduce**

**Expected behavior**

**Logs**

when i ran flatpak run --user com.jagex.Launcher i got the error: app/com.Jagex.Launcher/aarch64/master not installed
<summary>
Flatpak Log
<details>

```text
LOGS GO HERE
```

</details>
</summary>

**Screenshots**

**System**
 - OS: Ubuntu
 - GPU Vendor:  

**Additional context**
Again im new to linux so any help would be appreciated as i have no idea what part/step im missing

**Comment by USA-RedDragon** [comment]
Hello,

From the `aarch64` in the output, it looks like it's trying to install an ARM64 version, but this Flatpak doesn't work on ARM machines yet. I've actually got an arm machine in the last few days so I may go see about the viability of arm support.

**Comment by USA-RedDragon** [comment]
Looks like since the base build is multiarch, flatpak-builder has no way of conditionally excluding packages causing the build to always fail: https://github.com/flatpak/flatpak-builder/issues/381. So currently ARM support is not viable
