### ISSUE TITLE
Install script not parsing out correct field for nvidia driver version

### ISSUE THREAD

**Issue by tired-runner** [USA-RedDragon/jagex-launcher-linux-flatpak#116]
This is an issue with (choose one or more):

- [ ] RS3
- [ ] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [X] Something else

**Describe the bug**
When installing, the NVIDIA_VERSION variable gets set to "for" instead of the version

**To Reproduce**
1. use the installation script from the readme with open nvidia kernel module (I don't have a system with the non open kernel module to test with, but I assume the issue is they added more words to the first line of the /proc/driver/nvidia/version output)

**Expected behavior**

Should get the version field and install the dependency

**Logs**

<summary>
Flatpak Log
<details>

```text
LOGS GO HERE
```

</details>
</summary>

**Screenshots**
![Screenshot from 2024-10-19 11-08-47](https://github.com/user-attachments/assets/a457dbc8-8cbd-4151-bb34-ff090300fcc7)

**System**
 - OS: Bazzite (based off fedora 40)
 - GPU Vendor:  Nvidia

**Additional context**

On my machine at least, this would work to extract the version, but I am not so familiar with bash best practices
`cat /proc/driver/nvidia/version | head -n 1 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | sed 's/\./-/g'`

**Comment by USA-RedDragon** [comment]
Could you send the contents of `cat /proc/driver/nvidia/version` so I can see what changed about the output? Thanks

**Comment by tired-runner** [comment]
Here's the output:
`NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.35.03  Release Build  (dvs-builder@U16-I1-N07-12-3)  Fri Aug 16 21:42:42 UTC 2024
GCC version:  gcc version 14.2.1 20240912 (Red Hat 14.2.1-3) (GCC) `
