### ISSUE TITLE
nothing matches com.jagex.launcher

### ISSUE THREAD

**Issue by Tewaltsp** [USA-RedDragon/jagex-launcher-linux-flatpak#124]
This is an issue with (choose one or more):

- [ ] RS3
- [ *] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

Nothing matches com.jagex.Launcher.ThirdParty.RuneLite in remote JagexLauncher<summary>
Flatpak Log
<details>

```text
LOGS GO HERE
```

</details>
</summary>

**Screenshots**

**System**
 - OS: Version 132.0.6834.21 (Official Build) dev (64-bit) - GPU Vendor:  

**Additional context**
I downloaded runelite no problem and played for a few days but I have had a problem with getting hacked so I added my account to jagex and now I cant get the launcher to work. Keeps  telling me there is no match. I have tried everything I know how to do.

**Comment by USA-RedDragon** [comment]
Hello, what sort of system is this? I noticed you mention `Version 132.0.6834.21 (Official Build) dev (64-bit)`, is this ChromeOS? In particular, which CPU is in it? If it's ARM-based, multiarch Flatpak support is not yet viable: https://github.com/USA-RedDragon/jagex-launcher-linux-flatpak/issues/115#issuecomment-2424097660

**Comment by USA-RedDragon** [comment]
Yep, arm device. Since this flatpak doesn't have arm support, I recommend Bolt launcher (https://github.com/Adamcake/Bolt https://flathub.org/apps/com.adamcake.Bolt) as it should work on Chromebooks.
