### ISSUE TITLE
RS3 client doesn't utilize gpu

### ISSUE THREAD

**Issue by verlangen** [USA-RedDragon/jagex-launcher-linux-flatpak#126]
This is an issue with (choose one or more):

- [ x ] RS3
- [ ] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**
I recently upgraded from fedora 40 to fedora 41. After the upgrade when trying to play rs3 I noticed issues with the game. My cpu usage was spiking when the client was open. Figuring something broke with the upgrade, i removed all the flatpaks and reinstalled them. After a fresh install following the manual instructions, my rs3 client still isn't utilizing my nvidia gpu and is very cpu heavy. I'm seeing my cpu spike from around 6% idle usage to 50-60% just by running the rs3 client. When checking gpu process its listed but with very minimal resources used. The launcher itself as well as runelite are also listed and seems to be using the gpu just fine. 

**To Reproduce**
1. Remove all existing flatpaks related to this project
2. Reinstall them following the instructions under manual installation
3. Since I have an nvidia gpu install the proper nvidia package for my drivers (565.77)
4. Run the jagex launcher and then the rs3 client

**Expected behavior**
the rs3 client to use my gpu and not tax my cpu

**Logs**

<summary>
Flatpak Log

[flatpak_log.txt](https://github.com/user-attachments/files/18219517/flatpak_log.txt)

</summary>

**Screenshots**
I've attached 3 screenshots from my btop as a way to show cpu usage. If theres a better output that'd help you please let me know.
![jagex launcher](https://github.com/user-attachments/assets/eb6a91fb-d7dc-4111-a88c-e148922af966)
![rs3 client recommended](https://github.com/user-attachments/assets/ea8a3690-919d-4b5c-a51c-0c3c5267ac3b)
![rs3 client min detail](https://github.com/user-attachments/assets/2aca8ca5-3780-416a-99e3-8ee7887913e4)

**System**
 - OS: Fedora Workstation 41 - running wayland + hyprland
 - GPU Vendor:  Nvidia (evga geforce rtx 3090 ti)

**Additional context**
I have provided a gpu usage.txt file (output of nvidia-smi at different stages) as well as a flatpaks.txt showing what i currently have installed (output of flatpaks list). If theres anything else I can do/provide let me know and happy holidays :)
[gpu usage.txt](https://github.com/user-attachments/files/18219500/gpu.usage.txt)
[flatpaks.txt](https://github.com/user-attachments/files/18219501/flatpaks.txt)

**Comment by OHeggum** [comment]
### I am having the same issue
**System**

- OS: 6.11.11-1-MANJARO with xfce, if thats relevant. GPU 
- GPU: Nvidia RTX3050 Mobile with driver version 550.135

![image](https://github.com/user-attachments/assets/6cfa671d-bcb0-47ba-97ae-1cccd0edbd89)

**Comment by MushyMarks** [comment]
Can reproduce on 30 series card also (rtx 3060, hyprland, cachyos)...

Came here from bolt launcher, same there too.

**Comment by tired-runner** [comment]
I also see this issue on a 3080. A workaround is to use flatseal to apply the environment variable 
`MESA_LOADER_DRIVER_OVERRIDE=zink`
like so
![Screenshot From 2024-12-18 15-36-09](https://github.com/user-attachments/assets/98f6d76e-06cf-4dc2-96a7-c0591ea6c24c)

on my system this makes the game properly utilize the gpu

**Comment by USA-RedDragon** [comment]
Interesting. This does seem to be related to NVidia cards specifically, I'm not able to reproduce the issue on AMD GPU systems. I'm curious if the `MESA_LOADER_DRIVER_OVERRIDE=zink` variable resolves the issue for other folks in this thread. This Flatpak used to contain that by default, but I had to revert it due to issue #16.

**Comment by MushyMarks** [comment]
Can confirm setting '''MESA_LOADER_DRIVER_OVERRIDE=zink''' variable has resolved the issue...

**Comment by verlangen** [comment]
Can confirm that using flatseal to override the variable to `MESA_LOADER_DRIVER_OVERRIDE=zink` did fix the issue on my end. Thanks! Cpu usage is back to the normal and gpu is reporting 1300 MiB vs the previous 4MiB of mem. Is there anything else you want to see/ have me try or are we good to close out the issue?

**Comment by USA-RedDragon** [comment]
Hmm. I'd like to add some guidance about this to the readme, but I'm not sure what set of Nvidia folks are affected. The only common thread I've seen is these all seem to be 3000-series cards. Are the folks affected using the new open GPU modules? 

To tell you can look for `Open Kernel Module` in `/proc/driver/nvidia/version`

**Comment by MushyMarks** [comment]
> Hmm. I'd like to add some guidance about this to the readme, but I'm not sure what set of Nvidia folks are affected. The only common thread I've seen is these all seem to be 3000-series cards. Are the folks affected using the new open GPU modules? 
> 
> To tell you can look for `Open Kernel Module` in `/proc/driver/nvidia/version`

Hi hi, currently using the open kernel and confirmed in `/proc/driver/nvidia/version` but I also installed the proprietary version instead whilst trying to figure this out in early stages, made no difference as far as I can tell...

I'd be happy to just call it a Nvidia problem, 30 series cards are just more common I think...

**Comment by verlangen** [comment]
I have the proprietary drivers installed, haven't tested with the open kernel ones

**Comment by DevAndersen** [comment]
Just to confirm, I've also been experiencing this issue, and setting the `MESA_LOADER_DRIVER_OVERRIDE=zink` environment variable in Flatseal does indeed resolve the issue.

**System:** Arch, Linux kernel 6.12.7, KDE Plasma 6.1 (Wayland session)
**GPU:** GTX 970, NVIDIA proprietary driver 565.77-2 (DKMS)
