### ISSUE TITLE
Broken audio

### ISSUE THREAD

**Issue by t0msk** [USA-RedDragon/jagex-launcher-linux-flatpak#82]
This is an issue with (choose one):

- [+] RS3
- [ ] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**
Problem is that when I start music or during login screen, or during voice acting (quests) I have broken audio, I see cracking, I mean I hear audio with with cracking and it is really unpleasant to hear, I use pipewire as audio server.

**System**
 - OS: Arch Linux
 - GPU Vendor:  Nvidia

**Comment by nmlynch94** [comment]
> This is an issue with (choose one):
> 
> * [+] RS3
> * [ ]  Official Jagex OSRS
> * [ ]  RuneLite
> * [ ]  HDOS
> * [ ]  Something else
> 
> **Describe the bug** Problem is that when I start music or during login screen, or during voice acting (quests) I have broken audio, I see cracking, I mean I hear audio with with cracking and it is really unpleasant to hear, I use pipewire as audio server.
> 
> **System**
> 
> * OS: Arch Linux
> * GPU Vendor:  Nvidia

Try tweaking `PULSE_LATENCY_MSEC`. E.g. `flatpak run --env=PULSE_LATENCY_MSEC=200 com.jagex.Launcher`. You can tweak the value up or down until the audio hopefully smooths over. You can set it permanently in flatseal once you find a good value.

**Comment by USA-RedDragon** [comment]
Yep, what @nmlynch94 said, thanks for looking out. I was on vacation this week, sorry for not getting back to ya @t0msk !

Just pulling what seemed to work from the Tormstorm Discord since someone recently had the same issue:

> Assuming RS3, `PULSE_LATENCY_MSEC` might need some adjustments. This old thread has some info about this issue: https://old.reddit.com/r/runescape/comments/9xljkn/audio_problems_on_linux_version_of_nxt/ and this seems to be relevant if you're using Pipewire: https://forum.manjaro.org/t/howto-troubleshoot-crackling-in-pipewire/82442
> 
> The gist of updating the `PULSE_LATENCY_MSEC` for the Flatpak is to invoke it like: `flatpak run --user --env=PULSE_LATENCY_MSEC=### com.jagex.Launcher`, replacing `###` with a number. The default in my Flatpak is `256`, but it might need to be raised or lowered until audio is consistent.

**Comment by t0msk** [comment]
Thanks it works :) I was trying values 128, 200, 256, 400, and only at 200 it works working alright :) so I kept value of 200, btw I wonder how did you manage to include Jagex Launcher inside flatpack, I was trying to install Jagex Launcher in many Wine prefixes, but I always crashed on error like I don't have compatible Internet Explorer installed :D I even tried to instal MS Edge inside Wine prefix without success :D but yeah your flatpak works it is only one option to play RS on Linux right now :D

**Comment by nmlynch94** [comment]
> Thanks it works :) I was trying values 128, 200, 256, 400, and only at 200 it works alright :) so I kept value of 200, btw I wonder how did you manage to include Jagex Launcher inside flatpack, I was trying to install Jagex Launcher in many Wine prefixes, but I always crashed on error like I don't have compatible Internet Explorer installed :D I even tried to instal MS Edge inside Wine prefix without success :D but yeah your flatpak works it is only one option to play RS on Linux right now :D

The launcher itself runs pretty easily in wine. The problem is the installer as you've found out.

We got it running at one point, but it was always dicey at best, failing seemingly due to some sort of race-condition or something on some hardware and we had to hack around a freezing issue during the installation prompts as well. This was a few months ago so I don't know if it still works at all of not. I finally got a python script working to install the launcher headlessly a few months back after bashing my head against it for while, and then @USA-RedDragon greatly improved upon it. All of these changes together made it much more reliable to run, and feasible to bundle it into a flatpak even though it still has issues. 

There also is actually another option to play RS on linux besides wine: https://flathub.org/apps/com.adamcake.Bolt

**Comment by USA-RedDragon** [comment]
^^ and second for Bolt, it's a great option too.

**Comment by t0msk** [comment]
Yeah I had some strange issues with your launcher, like it was working one day and other day it wont open anymore, but it was like one month ago :dagger: 

I tried to install jagex launcher downloaded from jagex website using Lutris and Bottles, and never had success with it :D

Hmm Bolt, I see, but it is missing UI somehow :D but it works too as I tried it, I mean if they included some UI and maybe renamed it to something more like RuneScape-like it would be good step :D (like an-anime-game launcher for Genshin Impact) they created own UI (similar to official Windows launcher), so if Bolt would recreate somehow Jagex launcher feel :D
