### ISSUE TITLE
app/com.jagex.launcher/x86_64/master not installed

### ISSUE THREAD

**Issue by radianthero** [USA-RedDragon/jagex-launcher-linux-flatpak#85]
This is an issue with (choose one):

- [ ] RS3
- [ ] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [X ] Something else

**Describe the bug**
Followed the steps for the Flatpack, but I get a "Unfortunately the Jagex Launcher was not able to start. please check your connection and try restarting the launcher"

I tried  #37 fix by using `latpak run --user com.jagex.Launcher` but it still gave the same error. 

**To Reproduce**
Fresh install of Arch Linux,
Follow the steps to install everything through flatpak
Run the program

**Expected behavior**
Start the Jagex Launcher

**Screenshots**

**System**
 - OS: Arch Linux 
 - GPU Vendor:  nvidia

**Additional context**
https://pastebin.com/rPAthRRh error message.

**Comment by USA-RedDragon** [comment]
I believe this is fixed in https://github.com/USA-RedDragon/jagex-launcher-linux-flatpak/commit/e2ea9c70784d3310ff407099c89e82f9cd6b92f9. The new build is released already. 

I was able to reproduce the GL context issues and keeping these files seems to resolve it.
