### ISSUE TITLE
Launcher does not run after updating to nvidia beta 555

### ISSUE THREAD

**Issue by xsghetti** [USA-RedDragon/jagex-launcher-linux-flatpak#86]
This is an issue with (choose one):

- [ ] RS3
- [ ] Official Jagex OSRS
- [ x] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**
After upgrading to the Nvidia 555 Beta Drivers the jagex launcher does not run

**To Reproduce**
clone the nvidia-dkms-beta, nvidia-utils-beta, and lib32-nvidia-utils-beta drivers from the AUR
run makepkg and makepkg -d for lib32-nvidia-utils-beta

Once you have built them all, move all of the pkg.tar.zst files into an empty directory together, and then  pacman -Ud *.pkg.tar.zst

reboot

**Expected behavior**
The launcher to run lol

**Screenshots**

**System**
 - OS: Arch
 - GPU Vendor:  Geforce RTX 3070

**Additional context**
Logs
https://pastebin.com/uurvn3bP

**Comment by USA-RedDragon** [comment]
I don't expect this to work until there are associated driver releases for Flatpak: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia which likely won't occur until the driver it out of beta. I appreciate the excitement for 555, but it's not time yet.

**Comment by xsghetti** [comment]
Seems like there was a PR for a 555 beta driver that now has the launcher running!
