### ISSUE TITLE
Jagex Launcher error on update, can't launch

### ISSUE THREAD

**Issue by frederickjjoubert** [USA-RedDragon/jagex-launcher-linux-flatpak#97]
This is an issue with (choose one):

- [ ] RS3
- [x] Official Jagex OSRS
- [ ] RuneLite
- [ ] HDOS
- [ ] Something else

**Describe the bug**

I open the launcher, I need to update and restart, the update starts, and then errors out with `Error: The launcher has experienced an error and needs to close.`

**To Reproduce**

Open the launcher.

**Expected behavior**

The update should complete successfully, I have been using the launcher for about a year now without issue.

**Screenshots**

![Photo Jul 09 2024, 16 42 53](https://github.com/USA-RedDragon/jagex-launcher-linux-flatpak/assets/20562845/f5b779f6-8704-4cf6-a482-7d1ad5d05768)
![Photo Jul 09 2024, 16 43 24](https://github.com/USA-RedDragon/jagex-launcher-linux-flatpak/assets/20562845/b8c1dbb2-1dd9-4344-af5e-a309a7d0bae7)

**System**
 - OS: PopOS 22.04
 - GPU Vendor:  NVIDIA 2080 Ti

**Additional context**

I've been using this flatpak launcher without issue for a long time now, I think this started with the most recent flatpak update.

**Comment by USA-RedDragon** [comment]
Yeah I suspect this is because I fell slightly behind on getting v1.0.0 of the launcher in the Flatpak (https://github.com/USA-RedDragon/jagex-launcher-linux-flatpak/pull/95). I merged it in, there should be an update to the Flatpak in about an hour once CI finishes.

**Comment by frederickjjoubert** [comment]
Awesome! I updated the flatpak following your new update and it's working again!

Thank you very much for maintaining this project, I really appreciate your time and effort. I use this daily to play OSRS on my PopOS machine and it brings me much joy. Thank you. All the best.
